### ISSUE TITLE
Where to find the mirrord Formula

### ISSUE THREAD

**Issue by f-blass** [metalbear-co/homebrew-mirrord#1]
Happy to see that there apparently is a homebrew formula for mirrord. Unfortunately I was not able to find it on my M1 MacBook. Also on the Homebrew website I cannot find it: https://formulae.brew.sh/formula/

Do you have to add another tap?

**Comment by eyalb181** [comment]
Hey @f-blass, how did you try to install it? Either of these should work:
`brew install metalbear-co/mirrord/mirrord`
or
```
brew tap metalbear-co/mirrord
brew install mirrord
```

Please let us know if neither work for you and we'll look into it.

**Comment by f-blass** [comment]
Thank you @eyalb181 !

I was not aware that I have to add the third party repository `metalbear-co/mirrord` but thought it was part of the official Homebrew repo. Maybe this can be added as installation guide to the README. Thanks for the clarification!

**Comment by eyalb181** [comment]
@f-blass Added to README, appreciate the feedback!
